# Generated by Django 4.2.5 on 2023-09-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_url_link_remove_url_uuid_url_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='url',
            name='original_url',
        ),
        migrations.RemoveField(
            model_name='url',
            name='shortened_url',
        ),
        migrations.AddField(
            model_name='url',
            name='generated_link',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='real_url',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='url_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
